password.directory: E:\demo\src\main\resources\pwd

database:
#  url: jdbc:mysql://localhost:3307/demo?serverTimezone=JST&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
  url: jdbc:mysql://localhost:3307/my_data
  user: root
  driver.class.name: com.mysql.cj.jdbc.Driver

# app value
token.expiration: 1